---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Engineering Managers Slack Group"
keywords:    "engineering managers, vp engineering, engineering, leadership, technology, programming, software, development, slack"
description: "Public landing page for the Engineering Managers Slack group. Read the Code of Conduct and request an invite here."
source_link: "http://engmanagers.github.io"
favicon:     "img/favicon.ico"
touch_icon: # "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  red:			'#E85B57'
  orange:		'#F59B5B'
  yellow:		'#F8D57A'
  lightgreen:	'#3EE965'
  darkgreen:	'#14C782'
  blue:			'#00C0FC'
  indigo:		'#5A81FF'
  purple:		'#5D19AF'
  green:     '#9bcf2f'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
